/* eslint-disable no-shadow */


export enum PeopleTypes {
    PEOPLE_CREATE_SUCCESS = 'PEOPLE_CREATE_SUCCESS',
    PEOPLE_CREATE_REQUEST = 'PEOPLE_CREATE_REQUEST',
    PEOPLE_CREATE_FAILURE = 'PEOPLE_CREATE_FAILURE'
}